// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASc6HLnHoQnA5DRe3O_5BCFczr5nX_bsE',
    appId: '1:689304516125:web:3fefa4ca584f224721f8f4',
    messagingSenderId: '689304516125',
    projectId: 'vallarta-restaurant',
    authDomain: 'vallarta-restaurant.firebaseapp.com',
    databaseURL: 'https://vallarta-restaurant-default-rtdb.firebaseio.com',
    storageBucket: 'vallarta-restaurant.appspot.com',
    measurementId: 'G-BWW6HW7673',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgaYRcLXRi9QPEZL2NNhZlxr6U52nuS8',
    appId: '1:689304516125:android:d20270b8aa34701b21f8f4',
    messagingSenderId: '689304516125',
    projectId: 'vallarta-restaurant',
    databaseURL: 'https://vallarta-restaurant-default-rtdb.firebaseio.com',
    storageBucket: 'vallarta-restaurant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHsDVvJXipuGwoQeR5VcJMeAiU19g4eiU',
    appId: '1:689304516125:ios:ba45d2f6cf845cd921f8f4',
    messagingSenderId: '689304516125',
    projectId: 'vallarta-restaurant',
    databaseURL: 'https://vallarta-restaurant-default-rtdb.firebaseio.com',
    storageBucket: 'vallarta-restaurant.appspot.com',
    iosClientId: '689304516125-4cgnlp1670r1i5ouqfn5dn4j4ah0tkqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.vallartaApp',
  );
}
